export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export type ADD_INGREDIENT  = typeof ADD_INGREDIENT;

export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export type REMOVE_INGREDIENT  = typeof REMOVE_INGREDIENT;
