export const ADD_INGREDIENT  = 'ADD_INGREDIENT';
export type  ADD_INGREDIENT  = typeof ADD_INGREDIENT;

export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export type  REMOVE_INGREDIENT =  typeof REMOVE_INGREDIENT;

export const SET_INGREDIENTS  = 'SET_INGREDIENTS';
export type  SET_INGREDIENTS  =  typeof SET_INGREDIENTS;

export const FETCH_INGREDIENTS_FAILED  = 'FETCH_INGREDIENTS_FAILED';
export type  FETCH_INGREDIENTS_FAILED  =  typeof FETCH_INGREDIENTS_FAILED;

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export type  PURCHASE_BURGER_START =  typeof PURCHASE_BURGER_START;

export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export type  PURCHASE_BURGER_SUCCESS =  typeof PURCHASE_BURGER_SUCCESS;

export const PURCHASE_BURGER_FAILED = 'PURCHASE_BURGER_FAILED';
export type  PURCHASE_BURGER_FAILED =  typeof PURCHASE_BURGER_FAILED;

export const PURCHASE_INIT = 'PURCHASE_INIT';
export type  PURCHASE_INIT =  typeof PURCHASE_INIT;

export const FETCH_ORDERS = 'FETCH_ORDERS';
export type  FETCH_ORDERS =  typeof FETCH_ORDERS;

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export type  FETCH_ORDERS_START =  typeof FETCH_ORDERS_START;

export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export type  FETCH_ORDERS_SUCCESS =  typeof FETCH_ORDERS_SUCCESS;

export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';
export type  FETCH_ORDERS_FAILED =  typeof FETCH_ORDERS_FAILED;

export const AUTH_START = 'AUTH_START';
export type  AUTH_START =  typeof AUTH_START;

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export type  AUTH_SUCCESS =  typeof AUTH_SUCCESS;

export const AUTH_FAIL = 'AUTH_FAIL';
export type  AUTH_FAIL =  typeof AUTH_FAIL;

export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export type  AUTH_LOGOUT =  typeof AUTH_LOGOUT;

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export type  SET_AUTH_REDIRECT_PATH =  typeof SET_AUTH_REDIRECT_PATH;
